# CC=gcc
# CXX=g++
# RM=rm -f
# CPPFLAGS=-g $(shell root-config --cflags)
# LDFLAGS=-g $(shell root-config --ldflags)
# LDLIBS=$(shell root-config --libs)

# SRCS=tool.cc support.cc
# OBJS=$(subst .cc,.o,$(SRCS))

# all: tool

# tool: $(OBJS)
#     $(CXX) $(LDFLAGS) -o tool $(OBJS) $(LDLIBS)

# tool.o: tool.cc support.hh

# support.o: support.hh support.cc

# clean:
#     $(RM) $(OBJS)

# distclean: clean
#     $(RM) tool
# EXE = main
# OBJS = main.o
# CLEAN_RM =

# EXE = main
# OBS = main.o ../common/*.hpp
# CLEAN_RM = 

# include ../generic.mk

# all: day5
# day5: day5.cpp
# 	cpp day5.cpp -o ../build/day5

EXE = ../build/day4
OBJS = day4.o
CLEAN_RM =

include ../generic.mk
